### ISSUE TITLE
When testing a picture, the size of the result picture is different from that of the original picture

### ISSUE THREAD

**Issue by Magic-123** [jannctu/Rcf-Pytorch-Wrapper#2]
Hello, I'd like to ask you how the size of the original map is different from that of the original map after it passes through the network? What needs to be done to make the resulting graph the same size as the original one?

**Comment by jannctu** [comment]
Hi @Magic-123 

The size output should be the same as the original input. 

If there are some different then, you may check out at 
1. The dataloader, do you resize the input image? I forgot, did I resize or not. 
people usually resize the image size, because they wanna use batch-size > 1. 
2. Check out the cropping function on the upsample part (network.py)
3. If you still have different sizes, then just resize back to the original size. (bilinear interpolation can be used)

hope it helps.  
Thanks 
Jan

**Comment by Magic-123** [comment]
thanks
